
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Krystle
 */
public class MenuGUI extends javax.swing.JFrame {

    /**
     * Creates new form MenuGUI
     */
    public MenuGUI() throws IOException {
        loadNewMenu("menu.txt");
//        m = new Menu("test menu");
//        m.addMenuItem(new MenuItem("Hamburger",1.0));
//        m.addMenuItem(new MenuItem("CheeseBurger",2.0));
//        m.addMenuItem(new MenuItem("Hamburger",1.0));
//        m.addMenuItem(new MenuItem("Bacon",2.0));
//        m.addMenuItem(new MenuItem("abc",1.0));
//        m.addMenuItem(new MenuItem("def",2.0));
//        m.addMenuItem(new MenuItem("ghi",1.0));
//        m.addMenuItem(new MenuItem("jkl",2.0));
//        m.addMenuItem(new MenuItem("Hamburger",1.0));
//        m.addMenuItem(new MenuItem("CheeseBurger",2.0));
//        m.addMenuItem(new MenuItem("Hamburger",1.0));
//        m.addMenuItem(new MenuItem("Bacon",2.0));
//        m.addMenuItem(new MenuItem("abc",1.0));
//        m.addMenuItem(new MenuItem("def",2.0));
//        m.addMenuItem(new MenuItem("ghi",1.0));
//        m.addMenuItem(new MenuItem("jkl",2.0));
//        m.addMenuItem(new MenuItem("Hamburger",1.0));
//        m.addMenuItem(new MenuItem("CheeseBurger",2.0));
//        m.addMenuItem(new MenuItem("Hamburger",1.0));
//        m.addMenuItem(new MenuItem("Bacon",2.0));
//        m.addMenuItem(new MenuItem("abc",1.0));
//        m.addMenuItem(new MenuItem("def",2.0));
//        m.addMenuItem(new MenuItem("ghi",1.0));
//        m.addMenuItem(new MenuItem("jkl",2.0));
//      
        currentOrder = new Order();
        initComponents();
        generateButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonFillPanel = new javax.swing.JPanel();
        orderPanel = new javax.swing.JPanel();
        payButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderHistoryText = new javax.swing.JTextArea();
        cancelButton = new javax.swing.JButton();
        currentTotalText = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POS SYSTEM");
        setMinimumSize(null);
        setName(""); // NOI18N

        buttonFillPanel.setLayout(new java.awt.GridLayout((int)Math.floor(Math.sqrt(mr.menu.menuItemList.size())), 0));

        payButton.setText("Pay");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });

        orderHistoryText.setColumns(20);
        orderHistoryText.setRows(5);
        orderHistoryText.setFocusable(false);
        jScrollPane1.setViewportView(orderHistoryText);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        currentTotalText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        currentTotalText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        currentTotalText.setText("0");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setLabelFor(currentTotalText);
        jLabel2.setText("Current Total:");

        javax.swing.GroupLayout orderPanelLayout = new javax.swing.GroupLayout(orderPanel);
        orderPanel.setLayout(orderPanelLayout);
        orderPanelLayout.setHorizontalGroup(
            orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderPanelLayout.createSequentialGroup()
                .addComponent(cancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentTotalText, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(payButton, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        orderPanelLayout.setVerticalGroup(
            orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(payButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(currentTotalText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonFillPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(orderPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonFillPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(orderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
        // TODO add your handling code here:
        String cc = JOptionPane.showInputDialog(null,"Enter Credit Card Number");
        
//        if(CreditCard.isValid(cc)){
//            CreditCard = new CreditCard(cc);
//            //valid so go through
//            currentOrder.cc = new CreditCard(cc);
            currentOrder.created= new Date();
            
            System.out.println(currentOrder.toString());
            JOptionPane.showMessageDialog(null,currentOrder.toString(),"Order Placed", JOptionPane.INFORMATION_MESSAGE);
            
//        }
        
    }//GEN-LAST:event_payButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        currentOrder = new Order();
        currentTotalText.setText("0.0");
        orderHistoryText.setText("");
    }//GEN-LAST:event_cancelButtonActionPerformed

    
    private void loadNewMenu(String fn) throws FileNotFoundException, IOException{
        //TODO LATER
         //setup menu
        mr = new MenuReader(fn);
        mr.readMenu();
    }
    private void generateButtons(){
        for(int i=0;i<mr.menu.menuItemList.size();i++){
            
            MenuItem mi = (MenuItem) mr.menu.menuItemList.get(i);
            JButton b = new JButton(mi.getName());
            b.addActionListener((ActionEvent e) -> {
                currentOrder.addToOrder(mi);
                orderHistoryText.append(mi.getName() + " " + mi.getPrice() + "\n");
                //so that it doesnt go all long for some but small for others
                currentTotalText.setText( new DecimalFormat("#.##").format(currentOrder.total));
            });
            buttonList.add(b);
        }
       
        for(JButton b:buttonList){
            buttonFillPanel.add(b);
        }
        //this will resize based off of what buttons were generated
        pack();
    }
    /**
     * @param args the command line arguments
     * @throws java.io.FileNotFoundException
     */
    public static void main(String args[]) throws FileNotFoundException, IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                try {
                    new MenuGUI().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(MenuGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    
    private static Order currentOrder;
    private static MenuReader mr;
    private ArrayList<JButton> buttonList = new ArrayList<>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonFillPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel currentTotalText;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea orderHistoryText;
    private javax.swing.JPanel orderPanel;
    private javax.swing.JButton payButton;
    // End of variables declaration//GEN-END:variables
}
