

/**
 * Generated by NetBeans Swing GUI Panel template 
 * @author Krystle
 */
public class PointOfSaleGUI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public PointOfSaleGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        entreePanel = new javax.swing.JPanel();
        cheeseburgerButton = new javax.swing.JButton();
        corndogButton = new javax.swing.JButton();
        hotdogButton = new javax.swing.JButton();
        hamburgerButton = new javax.swing.JButton();
        nuggetButton = new javax.swing.JButton();
        sidesPanel = new javax.swing.JPanel();
        friesButton = new javax.swing.JButton();
        picklechipsButton = new javax.swing.JButton();
        curlyfryButton = new javax.swing.JButton();
        drinksPanel = new javax.swing.JPanel();
        cokeButton = new javax.swing.JButton();
        spriteButton = new javax.swing.JButton();
        waterButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        orderButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        entreePanel.setBackground(new java.awt.Color(204, 255, 204));
        entreePanel.setPreferredSize(new java.awt.Dimension(200, 0));

        cheeseburgerButton.setBackground(new java.awt.Color(153, 153, 255));
        cheeseburgerButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cheeseburgerButton.setText("Cheeseburger");
        cheeseburgerButton.setMargin(new java.awt.Insets(2, 20, 2, 20));

        corndogButton.setBackground(new java.awt.Color(153, 153, 255));
        corndogButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        corndogButton.setText("Corndog");
        corndogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corndogButtonActionPerformed(evt);
            }
        });

        hotdogButton.setBackground(new java.awt.Color(153, 153, 255));
        hotdogButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        hotdogButton.setText("Hot Dog");
        hotdogButton.setMargin(new java.awt.Insets(2, 20, 2, 20));

        hamburgerButton.setBackground(new java.awt.Color(153, 153, 255));
        hamburgerButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        hamburgerButton.setText("Hamburger");
        hamburgerButton.setMargin(new java.awt.Insets(2, 20, 2, 20));
        hamburgerButton.setMaximumSize(new java.awt.Dimension(115, 50));
        hamburgerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hamburgerButtonActionPerformed(evt);
            }
        });

        nuggetButton.setBackground(new java.awt.Color(153, 153, 255));
        nuggetButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nuggetButton.setText("Chicken Nuggets");
        nuggetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuggetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout entreePanelLayout = new javax.swing.GroupLayout(entreePanel);
        entreePanel.setLayout(entreePanelLayout);
        entreePanelLayout.setHorizontalGroup(
            entreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entreePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(entreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(hamburgerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hotdogButton)
                    .addComponent(cheeseburgerButton)
                    .addComponent(corndogButton)
                    .addComponent(nuggetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        entreePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cheeseburgerButton, corndogButton, hamburgerButton, hotdogButton, nuggetButton});

        entreePanelLayout.setVerticalGroup(
            entreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entreePanelLayout.createSequentialGroup()
                .addComponent(hamburgerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cheeseburgerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hotdogButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(corndogButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nuggetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        entreePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cheeseburgerButton, corndogButton, hamburgerButton, hotdogButton, nuggetButton});

        sidesPanel.setBackground(new java.awt.Color(204, 204, 255));
        sidesPanel.setPreferredSize(new java.awt.Dimension(200, 0));

        friesButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        friesButton.setText("Fries");
        friesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friesButtonActionPerformed(evt);
            }
        });

        picklechipsButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        picklechipsButton.setText("Pickle Chips");
        picklechipsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                picklechipsButtonActionPerformed(evt);
            }
        });

        curlyfryButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        curlyfryButton.setText("Curly Fries");

        javax.swing.GroupLayout sidesPanelLayout = new javax.swing.GroupLayout(sidesPanel);
        sidesPanel.setLayout(sidesPanelLayout);
        sidesPanelLayout.setHorizontalGroup(
            sidesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidesPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(sidesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(friesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(curlyfryButton)
                    .addComponent(picklechipsButton))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        sidesPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {curlyfryButton, friesButton, picklechipsButton});

        sidesPanelLayout.setVerticalGroup(
            sidesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidesPanelLayout.createSequentialGroup()
                .addComponent(friesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(curlyfryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(picklechipsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sidesPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {curlyfryButton, friesButton, picklechipsButton});

        drinksPanel.setBackground(new java.awt.Color(255, 204, 204));

        cokeButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cokeButton.setText("Coke");
        cokeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cokeButtonActionPerformed(evt);
            }
        });

        spriteButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        spriteButton.setText("Sprite");

        waterButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        waterButton.setText("Water");
        waterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout drinksPanelLayout = new javax.swing.GroupLayout(drinksPanel);
        drinksPanel.setLayout(drinksPanelLayout);
        drinksPanelLayout.setHorizontalGroup(
            drinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drinksPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(drinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(waterButton)
                    .addComponent(spriteButton)
                    .addComponent(cokeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        drinksPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cokeButton, spriteButton, waterButton});

        drinksPanelLayout.setVerticalGroup(
            drinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drinksPanelLayout.createSequentialGroup()
                .addComponent(cokeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spriteButton)
                .addGap(18, 18, 18)
                .addComponent(waterButton)
                .addGap(0, 190, Short.MAX_VALUE))
        );

        drinksPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cokeButton, spriteButton, waterButton});

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        orderButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        orderButton.setText("Place Order");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setText("Cancel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(orderButton))
            .addComponent(jScrollPane1)
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton2, orderButton});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton2, orderButton});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(entreePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sidesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(drinksPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(drinksPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(sidesPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                        .addComponent(entreePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hamburgerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hamburgerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hamburgerButtonActionPerformed

    private void corndogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corndogButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_corndogButtonActionPerformed

    private void nuggetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuggetButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuggetButtonActionPerformed

    private void friesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_friesButtonActionPerformed

    private void picklechipsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_picklechipsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_picklechipsButtonActionPerformed

    private void cokeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cokeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cokeButtonActionPerformed

    private void waterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_waterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PointOfSaleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PointOfSaleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PointOfSaleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PointOfSaleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PointOfSaleGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cheeseburgerButton;
    private javax.swing.JButton cokeButton;
    private javax.swing.JButton corndogButton;
    private javax.swing.JButton curlyfryButton;
    private javax.swing.JPanel drinksPanel;
    private javax.swing.JPanel entreePanel;
    private javax.swing.JButton friesButton;
    private javax.swing.JButton hamburgerButton;
    private javax.swing.JButton hotdogButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton nuggetButton;
    private javax.swing.JButton orderButton;
    private javax.swing.JButton picklechipsButton;
    private javax.swing.JPanel sidesPanel;
    private javax.swing.JButton spriteButton;
    private javax.swing.JButton waterButton;
    // End of variables declaration//GEN-END:variables
}
